version: '3.8'
services:
  postgres:
    build: .
    image: custom_postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  flask_app:
    build:
      context: .
      dockerfile: Dockerfile.flask
    container_name: flask_container
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_RUN_HOST=${FLASK_RUN_HOST}
      - FLASK_RUN_PORT=${FLASK_RUN_PORT}
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - SQLALCHEMY_TRACK_MODIFICATIONS=${SQLALCHEMY_TRACK_MODIFICATIONS}
    volumes:
      - .:/app
    ports:
      - "${FLASK_RUN_PORT}:${FLASK_RUN_PORT}"
    depends_on:
      - postgres
    networks:
      - app_network
    command: >
      bash -c "flask db upgrade && flask run --host=${FLASK_RUN_HOST} --port=${FLASK_RUN_PORT}"

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: